# Secret Scanning Custom Patterns
# https://docs.github.com/en/code-security/secret-scanning/defining-custom-patterns-for-secret-scanning

# This file helps GitHub detect custom secret patterns in your repository
# Patterns are regular expressions that match potential secrets

# SSH Private Keys - Multiple formats
- name: SSH Private Key (OpenSSH)
  pattern: '-----BEGIN OPENSSH PRIVATE KEY-----'
  confidence: high

- name: SSH Private Key (RSA)
  pattern: '-----BEGIN RSA PRIVATE KEY-----'
  confidence: high

- name: SSH Private Key (DSA)
  pattern: '-----BEGIN DSA PRIVATE KEY-----'
  confidence: high

- name: SSH Private Key (EC)
  pattern: '-----BEGIN EC PRIVATE KEY-----'
  confidence: high

- name: SSH Private Key (Encrypted)
  pattern: '-----BEGIN ENCRYPTED PRIVATE KEY-----'
  confidence: high

# PEM Format Keys
- name: PEM Private Key
  pattern: '-----BEGIN PRIVATE KEY-----'
  confidence: high

# AWS Keys
- name: AWS Access Key ID
  pattern: 'AKIA[0-9A-Z]{16}'
  confidence: high

- name: AWS Secret Access Key
  pattern: '(?i)aws_secret_access_key\s*=\s*["\']?[A-Za-z0-9/+=]{40}["\']?'
  confidence: high

# GitHub Tokens
- name: GitHub Personal Access Token
  pattern: 'gh[pousr]_[A-Za-z0-9_]{36,251}'
  confidence: high

- name: GitHub OAuth Token
  pattern: 'gho_[A-Za-z0-9_]{36,251}'
  confidence: high

# API Keys and Tokens
- name: Generic API Key
  pattern: '(?i)(api[_-]?key|apikey)\s*[:=]\s*["\']?[a-zA-Z0-9_\-]{20,}["\']?'
  confidence: medium

- name: Generic Secret
  pattern: '(?i)(secret|password|passwd|pwd)\s*[:=]\s*["\']?[^\s"\']{8,}["\']?'
  confidence: low

# OpenAI API Keys
- name: OpenAI API Key
  pattern: 'sk-[a-zA-Z0-9]{48}'
  confidence: high

# Slack Tokens
- name: Slack Token
  pattern: 'xox[baprs]-[0-9]{12}-[0-9]{12}-[a-zA-Z0-9]{24,32}'
  confidence: high

# Private Key File References (common mistakes)
- name: SSH Key File Reference
  pattern: '(?i)(id_rsa|id_dsa|id_ecdsa|id_ed25519)(?!\.pub)'
  confidence: medium

# Certificates
- name: SSL Certificate Private Key
  pattern: '-----BEGIN CERTIFICATE-----'
  confidence: medium

# Connection Strings
- name: Database Connection String
  pattern: '(?i)(mongodb|mysql|postgresql|mssql):\/\/[^\s"\']+:[^\s"\']+@'
  confidence: medium
